### ISSUE TITLE
你好，我在运行第二布的时候出现问题。

### ISSUE THREAD

**Issue by gaofei-coder** [veraposeidon/labelme2Datasets#1]
我在运行python bbox_labelme2voc.py --labels test/label_names.txt label_dict test/label_dict.txt test/test_jsons test/test_voc
需要改成

python bbox_labelme2voc.py --labels test/label_names.txt label_dict test/label_dict.txt test/test_jsons test/test_voc

**Comment by veraposeidon** [comment]
README文档中的确示例的确写错了，
应该将
`python bbox_labelme2voc.py --labels test/label_names.txt label_dict test/label_dict.txt test/test_jsons test/test_voc`
改为
`python bbox_labelme2voc.py --labels test/label_names.txt --label_dict test/label_dict.txt test/test_jsons test/test_voc`

如果用到`label_dict`的话，需要按照`--label_dict file_name`这样的形式来。
谢谢反馈。
