### ISSUE TITLE
no moudle named labelme

### ISSUE THREAD

**Issue by kungkook** [veraposeidon/labelme2Datasets#2]
When I run the bbox_labelme2voc. Py file, it shows no moudle named lanelme. Why?

**Comment by kungkook** [comment]
I have a new assertion error, as follows:
 if class_id == -1:
            assert class_name == '__ignore__'
            continue
        elif class_id == 0:
            assert class_name == '_background_'
My label_names.txt looks like this:
_background_
airport
background
How do I fix this？thank you！

**Comment by kungkook** [comment]
I have a new problem: line 79 of the program shows an error:

Typeerr :moudle object is not callable

**Comment by lmunan** [comment]
@kungkook I also encountered this problem, but I solved it. I added a sentence **`p = progressbar.ProgressBar()`** before line 79. Change line 79 to` for i in p(range(len(label_file_list))):`
