### ISSUE TITLE
标注数据

### ISSUE THREAD

**Issue by lyc1995452-star** [veraposeidon/labelme2Datasets#3]
你好，我已经得到标注，也进行训练了。但是我今天发现我标注得到的图片并没用很好的填充整个标注界面，
![0-5-1 10](https://user-images.githubusercontent.com/57827440/82559164-b5c75180-9ba1-11ea-9ee3-b0dc2318f21e.png)如这种，我想的是上下和左右都还有缝隙，原图却没有。

**Comment by veraposeidon** [comment]
没能理解你的意思。从这张标注图来看的话，有三种标注，黑色背景，红色和绿色是两种前景。
你是要达到什么效果呢？

**Comment by lyc1995452-star** [comment]
你好我想说的是我的圆没有正切这个方框，而原图是正切了的
![0-5-1 30](https://user-images.githubusercontent.com/57827440/82637609-b7435900-9c37-11ea-9a5d-44790218770e.png)
我想得到的是这种
![微信图片_20200522082415](https://user-images.githubusercontent.com/57827440/82637638-c75b3880-9c37-11ea-95e3-23f670b760a4.png)

**Comment by veraposeidon** [comment]
我估计你是用的带坐标轴的原图处理得到的标注图，建议你要用去掉坐标轴，只保留原图内容再做处理。
你贴出来的原图和你最开始放出来的图像尺寸是一样的，560*420，应该是这个问题。
