### ISSUE TITLE
你好，我在运行第二步的时候报错

### ISSUE THREAD

**Issue by gethubwy** [veraposeidon/labelme2Datasets#4]
AttributeError: module 'labelme.utils' has no attribute 'draw_instances'

**Comment by veraposeidon** [comment]
我看了下，是labelme更新了，丢掉了该接口。
我对照了下时间，你可以下载labelme 3.10.1 版本进行使用。https://github.com/wkentaro/labelme/tree/v3.10.1 
具体使用方式就是直接下载labelme的repo，将labelme文件夹放在工程目录下就好了。
