### ISSUE TITLE
执行脚本文件是出现问题： can not write mode RBGA as JPEG

### ISSUE THREAD

**Issue by lucafei** [veraposeidon/labelme2Datasets#6]
你好， 我使用labelme标注了我的数据集后，在使用你的脚本文件bbox_labelme2voc.py 时出现error：
![error](https://user-images.githubusercontent.com/29920326/95303937-2981a680-0884-11eb-9362-4549e493e36d.PNG)
请问这要怎么解决

**Comment by veraposeidon** [comment]
因为你待保存的图像数据是rgba四通道的，jpg不支持。
建议改成.png格式。
或者也可以将待保存的图像丢掉alpha通道。
