### ISSUE TITLE
labelme2voc

### ISSUE THREAD

**Issue by henbucuoshanghai** [veraposeidon/labelme2Datasets#7]
你好，lebelme标注的分割 不是一个个封闭的多边形   请问是怎样转换到一个个矩形bbox的？
labelme2voc里面？labelme标注的不是一个个封闭多边形？

**Comment by veraposeidon** [comment]
1. polygon转换到rectangle bbox，可以通过最小外接矩形计算得到，opencv有函数可以调用。
2. labelme2voc这个rep不支持没有该功能。
3. labelme[支持多种标注方式](https://github.com/wkentaro/labelme#description)，bbox和polygon是其中两种。labelme2voc支持bbox和segmentation两种形式。

polygon是比bbox更精准的标注，为何还要转换到bbox使用呢？

**Comment by henbucuoshanghai** [comment]
热心具体的回复。
polygon是比bbox更精准的标注，但是polygon是做分割用的，如果现在想做检测，不是需要换到矩形box？
cv2什么命令转换呢？
多谢

**Comment by veraposeidon** [comment]
最小外接矩形，minAreaRect

**Comment by henbucuoshanghai** [comment]
是的 明白。 最后一句根据polygon生成0，255的mask图  请问怎样生成呢？

**Comment by veraposeidon** [comment]
如果你是希望通过labelme的标注文件转换为segmentation图，可以参考labelme repo里的example。例如，https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation
